language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install liblo-dev

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest --output-on-failure
